# Owner review required before committing this file.
# Fill in the relevant platform keys, then commit:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
thanks_dev: u/gh/expert-vision-software
buy_me_a_coffee: expertvisionsoftware
